In [1]:

import pandas as pd
import pymongo

df = pd.read_csv('insurance_claim_data.csv')
df.head()

,incident_severity,insured_hobbies,incident_type,collision_type,incident_state,authorities_contacted,property_claim,vehicle_claim,policy_annual_premium,insured_zip,policy_number,total_claim_amount,months_as_customer,injury_claim,age,insured_occupation,capital-gains,fraud_reported
0,Major Damage,sleeping,Single Vehicle Collision,Side Collision,SC,Police,13020,52080,1406.91,466132,521585,71610,328,6510,48,craft-repair,53300,Y
1,Minor Damage,reading,Vehicle Theft,?,VA,Police,780,3510,1197.22,468176,342868,5070,228,780,42,machine-op-inspct,0,Y
2,Minor Damage,board-games,Multi-vehicle Collision,Rear Collision,NY,Police,3850,23100,1413.14,430632,687698,34650,134,7700,29,sales,35100,N
3,Major Damage,board-games,Single Vehicle Collision,Front Collision,OH,Police,6340,50720,1415.74,608117,227811,63400,256,6340,41,armed-forces,48900,Y
4,Minor Damage,board-games,Vehicle Theft,?,NY,NaN,650,4550,1583.91,610706,367455,6500,228,1300,44,sales,66000,N

In [2]:
# df should be converted into dict before we push it to mongodb

data = df.to_dict(orient='records')

In [ ]:
DB_NAME = "Insurance_Prediction_Proj"
COLLECTION_NAME = "Proj1-Data"
CONNECTION_URL = "mongodb+srv://<user_name>:<pass_word>@cluster0.qiyhijx.mongodb.net/?appName=Cluster0"

In [4]:

client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [5]:

# Uploading data to MongoDB
rec = collection.insert_many(data)

In [6]:

# Load back data from Mongodb
df = pd.DataFrame(list(collection.find()))
df.shape

(2000, 19)

In [7]:

df.head(3)

,_id,incident_severity,insured_hobbies,incident_type,collision_type,incident_state,authorities_contacted,property_claim,vehicle_claim,policy_annual_premium,insured_zip,policy_number,total_claim_amount,months_as_customer,injury_claim,age,insured_occupation,capital-gains,fraud_reported
0,69885fb0d0ef025ff748b5ad,Major Damage,sleeping,Single Vehicle Collision,Side Collision,SC,Police,13020,52080,1406.91,466132,521585,71610,328,6510,48,craft-repair,53300,Y
1,69885fb0d0ef025ff748b5ae,Minor Damage,reading,Vehicle Theft,?,VA,Police,780,3510,1197.22,468176,342868,5070,228,780,42,machine-op-inspct,0,Y
2,69885fb0d0ef025ff748b5af,Minor Damage,board-games,Multi-vehicle Collision,Rear Collision,NY,Police,3850,23100,1413.14,430632,687698,34650,134,7700,29,sales,35100,N